### ISSUE TITLE
Execution failed for task ':compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by tenji73** [katzer/cordova-plugin-badge#71]
hola,
i am getting this error when trying to build the android version:

```
:compileDebugJavaWithJavac/Users/tom/Documents/PhoneGapProjects/cs/platforms/android/src/de/appplant/cordova/plugin/badge/BadgeImpl.java:73: error: cannot find symbol
        ShortcutBadger badger = ShortcutBadger.with(ctx);
                                              ^
  symbol:   method with(Context)
  location: class ShortcutBadger
/Users/tom/Documents/PhoneGapProjects/cs/platforms/android/src/de/appplant/cordova/plugin/badge/BadgeImpl.java:75: error: incompatible types: ShortcutBadger cannot be converted to DefaultBadger
        return !(badger instanceof DefaultBadger);
                 ^
/Users/tom/Documents/PhoneGapProjects/cs/platforms/android/src/de/appplant/cordova/plugin/badge/BadgeImpl.java:87: error: cannot find symbol
        ShortcutBadger.with(ctx).remove();
                      ^
  symbol:   method with(Context)
  location: class ShortcutBadger
/Users/tom/Documents/PhoneGapProjects/cs/platforms/android/src/de/appplant/cordova/plugin/badge/BadgeImpl.java:122: error: cannot find symbol
            ShortcutBadger.with(ctx).count(badge);
                          ^
  symbol:   method with(Context)
  location: class ShortcutBadger
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

```

do you have any idea?
thanks!
tom

**Comment by mlabarca** [comment]
This looks like the dependency issue on v 1.7.1 that also makes my build fail on pgb. Did you try building using v1.7.2 locally ? (Note plugin id changes from that version onwards)

**Comment by clarklight** [comment]
@mlabarca Did you manage to get it working on PGB? with the version 0.7.2? I am getting a build error as well.

**Comment by mlabarca** [comment]
@clarklight  Not really, I ended up upgrading to the new push plugin just to get badges. It uses shortcutbadger too, but includes it via framework tags in the plugin .xml and then uses it in another way which doesn't prompt these kind of errors. I might end up forking this and including shortcutbadger that way to see if I can fix this, since I'm having more issues using the new push plugin.

**Comment by clarklight** [comment]
@mlabarca  ah ok..... cos i dont think i can use the new push plugin for my need......
from that error above it looks like the error is in BadgeImpl.java about symbol:   method with(Context), between the shortcutbadger and the BadgeImpl.java on all those 3 lines.... i am not sure if i am any good in Java to help....but will try to give it a look.

**Comment by katzer** [comment]
That has been fixed already
